
version: 2


jobs:
  build:
    machine:
    steps:
      - checkout
      - run:
          name: npm i & npm test
          command: |
            sudo apt-get update
            sudo curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo ln -s /usr/bin/nodejs /usr/bin/node
            sudo npm install -g npm
            sudo npm i
            sudo npm test