
version: 2


jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt-get remove nodejs
            sudo apt-get remove npm
            sudo apt-get update && apt-get -y upgrade
            curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g npm
      - run:
          name: node setup
          command: |
            nodejs -v
            npm -v
            npm i -g npm
      - run:
          name: prepare tests
          command: |
            sudo npm i
            sudo npm run test:compile
      - run:
          name: npm test
          command: |
            npm run test:exec
            ./node_modules/.bin/nyc report --reporter=json && ./node_modules/.bin/codecov -f coverage/*.json -t ${CODECOV_TOKEN}