
version: 2


jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: node setup
          command: |
            sudo apt-get update
            sudo curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g npm
      - run:
          name: prepare tests
          command: |
            sudo npm i
            sudo npm run test:compile
      - run:
          name: npm test
          command: |
            sudo npm run test:exec
            sudo env
            echo "AAAAA!!!!!!!!"
            echo env
            sudo ./node_modules/.bin/nyc report --reporter=json && ./node_modules/.bin/codecov -f coverage/*.json -t ${CODECOV_TOKEN}