
version: 2


jobs:
  build:
    machine:
      node:
        version: 9.3.0
    steps:
      - checkout
      - run:
          name: npm i & npm test
          command: |
            sudo apt-get update
            sudo apt-get install nodejs
            sudo apt-get install npm
            sudo npm install -g npm
            sudo npm i
            sudo npm test