
version: 2


jobs:
  build:
    machine:
      image: circleci/node:9.3.0
    steps:
      - checkout
      - run:
          name: node setup
          command: |
            npm i -g npm
      - run:
          name: prepare tests
          command: |
            sudo npm i
            sudo npm run test:compile
      - run:
          name: npm test
          command: |
            npm run test:exec
            ./node_modules/.bin/nyc report --reporter=json && ./node_modules/.bin/codecov -f coverage/*.json -t ${CODECOV_TOKEN}