
version: 2


jobs:
  build:
    machine:
      node:
        version: 8.2.0
    steps:
      - checkout
      - run:
          name: npm i & npm test
          command: |
            npm i
            npm test