
version: 2


jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
        name: npm i & npm test
        command: |
          sudo apt-get update
          sudo curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g npm
          sudo npm i
      - run:
          parallel: true
          command: |
            sudo npm run test:ci:1
      - run:
          parallel: true
          command: |
            sudo npm run test:ci:2
            sudo npm run test:ci:3