
version: 2


jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt-get -y update
            sudo curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g npm
      - run:
          name: node setup
          command: |
            nodejs -v
            npm -v
            npm i -g npm
      - run:
          name: prepare tests
          command: |
            npm i
            npm run test:compile
      - run:
          name: npm test
          command: |
            nodejs -v
            npm -v
            npm run test:exec
            ./node_modules/.bin/nyc report --reporter=json && ./node_modules/.bin/codecov -f coverage/*.json -t ${CODECOV_TOKEN}